name: "Build and Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - client/**
      
permissions:
  id-token: write
  contents: read

jobs:
    call-workflow-passing-data:
      uses: TomBenjaminMorris/github-actions-lib/.github/workflows/react-build-and-deploy.yml@master
      with:
        aws-default-region: eu-west-2
        tf-aws-role: ${{ vars.TF_AWS_ROLE }}
        domain-name: vinsp.in
        folder-name: client
      secrets: inherit
