name: BuildAndDeploy
on:
  workflow_dispatch:
#   push:
#     branches:
#       - master

permissions:
 id-token: write
 contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
     AWS_DEFAULT_REGION: eu-west-2
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 12
      uses: actions/setup-node@v3
      with:
        node-version: 12

    - name: Install Packages
      run: |
        npm install

    - name: Build React App
      run: |
        CI=false npm run build
        echo "Build complete 🏗️"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ vars.TF_AWS_ROLE }}
        role-session-name: samplerolesession
        aws-region: ${{env.AWS_DEFAULT_REGION}}

    - name: Sync S3 & Invalidate Caches
      run: |
        aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET }}
        dist1=`aws cloudfront list-distributions --query "DistributionList.Items[?Comment=='vinsp.in'].Id" --output text`
        dist2=`aws cloudfront list-distributions --query "DistributionList.Items[?Comment=='www.vinsp.in'].Id" --output text`
        aws cloudfront create-invalidation --distribution-id $dist1 --paths "/*"
        aws cloudfront create-invalidation --distribution-id $dist2 --paths "/*"
