name: "Terraform: Apply"

concurrency:
  group: deploy-test
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - terraform/**
      
permissions:
  id-token: write
  contents: read

jobs:
    call-workflow-passing-data:
      uses: TomBenjaminMorris/github-actions-lib/.github/workflows/terraform-deploy-on-pr-merge.yml@master
      with:
        aws-default-region: eu-west-2
        tf-aws-role: ${{ vars.TF_AWS_ROLE }}
        tf-version: "0.14.7"
      secrets: inherit