name: "Terraform: Validate and Plan"

concurrency:
  group: deploy-test
  cancel-in-progress: false

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - terraform/**
      
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
    call-workflow-passing-data:
      uses: TomBenjaminMorris/github-actions-lib/.github/workflows/terraform-test-on-pr.yml@master
      with:
        aws-default-region: eu-west-2
        tf-aws-role: ${{ vars.TF_AWS_ROLE }}
        tf-version: "0.14.7"
      secrets: inherit